package visual.util.forDBAction.enumeration;

public enum TypeInfo {
	SHOW_STUDENT,
	SHOW_DOCENT,
	SHOW_TECAD,
	SHOW_VISITOR,
	SHOW_RULES,
	SHOW_LOCALS,
	SHOW_REGISTRY_ACCESS,
	SHOW_REGISTRY_REQUEST_KEY,
	SHOW_SCHEME_ACCESS,
	SHOW_SCHEME_KEY_REQUEST,
	SHOW_REPORT_KEY_NOT_DELIVERY,
	SHOW_REPORT_ACCESS_WORKER,
	SHOW_REPORT_VISIT,
	SHOW_REPORT_REQUEST_DELIVERY_KEY,
	SHOW_REPORT_FIND_KEY,
	SHOW_REPORT_MORE_EXTRACTION,
	SHOW_ABOUT
}
